vikingco/unleashed-web-api-model

- README.md
- assets/sections/unleashed-web-api/templates/reference/customers.md
- definitions/customers/migrate_customer.yaml
- paths/customers/create.yaml
- paths/customers/email.yaml
- paths/customers/email_perform.yaml
- paths/customers/me.yaml
- paths/customers/migrate.yaml
- paths/customers/notifications.yaml
- paths/customers/verify.yaml
- paths/index.yaml
- paths/notifications/subscription_notification_settings.yaml
- swagger.yaml
Creating better documentation and conventions.
> Clean Customers section

- definitions/products/product.yaml
https://vikingco.atlassian.net/browse/UWA-419
> We do not get `order_parameters` and `payment_providers` via Comarch

- paths/telco/sim_via_icc_id.yaml
For the scenario were front-end aks short iccid. They will ask all customer sims,
and implement this logic there self
https://vikingco.atlassian.net/browse/UWA-416
> We will always ask full iccid

- definitions/subscriptions/subscription.yaml
https://vikingco.atlassian.net/browse/UWA-446
> Let subscription return full product

- definitions/subscriptions/subscription.yaml
To distinguish between owned and authorized subscription
https://vikingco.atlassian.net/browse/UWA-507
> Add field `owns` to subscription

- definitions/general/status.yaml
- paths/password/reset_perform.yaml
https://vikingco.atlassian.net/browse/UWA-552
Also checked other bad request codes, there was one other missing.
> Update perform password reset to match reality

- paths/products/list.yaml
https://vikingco.atlassian.net/browse/UWA-589
> Add filter `product_id` on product list

- definitions/authentication/access_token.yaml
- paths/authentication/access_token.yaml
- paths/authentication/revoke_token.yaml
https://vikingco.atlassian.net/browse/UWA-710
> Uwa 710/oath model

- paths/customers/me.yaml
https://vikingco.atlassian.net/browse/UWA-712
> We will pass social if we have the data

- definitions/subscriptions/balance.yaml
https://vikingco.atlassian.net/browse/UWA-509
> Product not required for balance

- definitions/products/product.yaml
https://vikingco.atlassian.net/browse/UWA-743
> Add `variant` to product

- assets/sections/unleashed-web-api/templates/guides/getting-started.md
- definitions/products/product_id.yaml
- definitions/subscriptions/create_subscription.yaml
- definitions/subscriptions/mgm.yaml
- definitions/telco/sim_details.yaml
Add format msisdn where applicable.
https://vikingco.atlassian.net/browse/UWA-824
> Add documentation on type msisdn and product_id

- paths/customers/verify.yaml
> verify should return 204

- definitions/finance/mandate.yaml
Comarch is returning this information.
> We needs to have expiration date on mandate

- definitions/finance/payment_method.yaml
SEPA is a mandate configured with SEPA
> SEPA ansich is not a payment method

- paths/finance/invoices.yaml
- paths/orders/create_and_list.yaml
- paths/orders/details.yaml
- paths/subscriptions/topups.yaml
- paths/subscriptions/usage.yaml
https://vikingco.atlassian.net/browse/UWA-1059 and
https://vikingco.atlassian.net/browse/UWA-1066
> Uwa 1059/cancel order

- paths/orders/create_and_list.yaml
https://vikingco.atlassian.net/browse/UWA-1091
> UWA-1091/We want to be able to filter on status of order

- parameters/index.yaml
There is `default` attribute but that is not shown in swagger
> Make more clear what default values are

- definitions/customers/verify.yaml
https://vikingco.atlassian.net/browse/UWA-949
> In case of e.g. resend, value is not needed

- definitions/orders/create_order.yaml
This way we can do orders with an easy payment/ automatic payment
https://vikingco.atlassian.net/browse/UWA-1328
> UWA-1328/Make it possible to pass mandate_id on create order

- definitions/general/status.yaml
https://vikingco.atlassian.net/browse/UWA-1368
> UWA-1368/Add field for invalid query parameter

- Dockerfile
The reason notifications was not shown as list is solved with new release.
https://vikingco.atlassian.net/browse/UWA-1190
> UWA-1190/Upgrade dapperbox

- definitions/general/status.yaml
For now thrown when you do topup on ported out subscription
https://vikingco.atlassian.net/browse/UWA-1567
> UWA-1567/Add error code for deactivated subscription

- definitions/orders/donor.yaml
https://vikingco.atlassian.net/browse/UWA-1736
> Msisdn is a required field for MNP details

- definitions/index.yaml
- definitions/subscriptions/subscription_service_settings.yaml
- definitions/subscriptions/subscription_service_settings_change.yaml
- definitions/subscriptions/subscription_service_settings_change_request.yaml
- paths/index.yaml
- paths/subscriptions/service_settings.yaml
https://vikingco.atlassian.net/browse/UWA-1797
> Add subscription service settings

- definitions/general/status.yaml
https://vikingco.atlassian.net/browse/INT-1968
> Distinct between migration pending on doing migrate or topup

- definitions/orders/order.yaml
https://vikingco.atlassian.net/browse/INT-2023
> INT-2023/Comarch added the state mnp_rejected as order status

- definitions/general/status.yaml
https://vikingco.atlassian.net/browse/INT-4848
> Add new doccle related exceptions

- definitions/customers/customer.yaml
- definitions/customers/loyalty_state_validity.yaml
- definitions/index.yaml
- definitions/loyalty/loyalty_transaction.yaml
- paths/loyalty/loyalty_transactions.yaml
https://vikingco.atlassian.net/browse/INT-4836
> Loyalty points expiration model updates

- definitions/subscriptions/balance.yaml
- definitions/subscriptions/usage.yaml
https://vikingco.atlassian.net/browse/INT-4936
> Add unlimited and throttled attributes

- paths/finance/invoices.yaml
https://vikingco.atlassian.net/browse/INT-4965
> Remove incorrect reference
